"""
database.py
------------
SQLite persistence layer for the Smart Road & Flyover Damage
Monitoring & Decision Intelligence System.

Owns ALL SQLite access for the Streamlit app - no other module should
open a connection directly.

SIX tables:

    road_assets   - one row per named road/flyover segment (id, name, type)
    detections    - every individual YOLOv8 finding (image or video frame)
    predictions   - one row per analysis session: health/risk/emergency/
                    repair-cost/RUL/recommendation, i.e. the full
                    decision-intelligence output for that session
    notifications - every alert dispatched by notification_service
    complaints     - every municipal complaint generated by complaint_service
    reports        - any exported report/PDF/CSV file reference

Design notes
------------
* road_id (an integer FK into road_assets) is the PRIMARY key app.py uses
  for every lookup/filter. A denormalized `road_name` column is also kept
  on every table for convenience/back-compat with older, name-keyed
  callers - it costs nothing and avoids a join for simple listing pages.
* road_id may be NULL: the sidebar lets a user run detection against
  "(New road/flyover)" before clicking "Create asset", so every write
  function accepts road_id=None gracefully.
* No FOREIGN KEY constraints are declared. This is deliberate: per spec,
  "No database errors should ever crash the app" - a strict FK constraint
  would raise on any orphaned/None reference, which is exactly the
  failure mode we're avoiding here. Referential integrity is maintained
  at the application layer instead.
* Every read function returns [] / {} / None on any error instead of
  raising, and logs the exception - see `_safe_list` / `_safe_dict`.
* `init_db()` is idempotent and additionally self-heals older database
  files: after CREATE TABLE IF NOT EXISTS, `_migrate_schema()` inspects
  each table's actual columns via PRAGMA table_info and ALTER TABLE ADD
  COLUMN's anything missing (e.g. an old DB created before `road_id`
  existed). This is what prevents the classic
  `sqlite3.OperationalError: no such column: ...` crash on startup.
* Connections are opened per-call (not held open) since Streamlit reruns
  the whole script on every interaction - this avoids "database is
  locked" / cross-thread sqlite3 errors without needing a connection pool.
"""

import json
import logging
import sqlite3
from contextlib import contextmanager
from functools import wraps
from pathlib import Path
from typing import Dict, List, Optional

logger = logging.getLogger("database")
logging.basicConfig(level=logging.INFO)

try:
    from config import DATABASE_PATH, SQLITE_TIMEOUT_SECONDS, ENABLE_FOREIGN_KEYS
except ImportError:
    DATABASE_PATH = Path("database/road_monitoring.db")
    Path(DATABASE_PATH).parent.mkdir(parents=True, exist_ok=True)
    SQLITE_TIMEOUT_SECONDS = 30
    ENABLE_FOREIGN_KEYS = True

DATABASE_PATH = Path(DATABASE_PATH)
DATABASE_PATH.parent.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------
# SCHEMA
# ---------------------------------------------------------------------
SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS road_assets (
    road_id         INTEGER PRIMARY KEY AUTOINCREMENT,
    name            TEXT NOT NULL UNIQUE,
    asset_type      TEXT CHECK(asset_type IN ('road','flyover')) DEFAULT 'road',
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS detections (
    detection_id    INTEGER PRIMARY KEY AUTOINCREMENT,
    road_id         INTEGER,
    road_name       TEXT,
    session_id      TEXT,
    asset_type      TEXT CHECK(asset_type IN ('road','flyover')) DEFAULT 'road',
    source_type     TEXT CHECK(source_type IN ('image','video','manual')) NOT NULL DEFAULT 'image',
    source_path     TEXT,
    source_filename TEXT,
    annotated_path  TEXT,
    class_name      TEXT NOT NULL,
    confidence      REAL NOT NULL,
    area_px         REAL,
    bbox_x1 REAL, bbox_y1 REAL, bbox_x2 REAL, bbox_y2 REAL,
    frame_number    INTEGER,
    timestamp_sec   REAL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS predictions (
    prediction_id       INTEGER PRIMARY KEY AUTOINCREMENT,
    road_id             INTEGER,
    road_name           TEXT,
    session_id          TEXT UNIQUE,
    asset_type          TEXT,
    damage_count        INTEGER,
    damage_percentage   REAL,
    severity_score      REAL,
    severity_class      TEXT,
    health_score        REAL,
    hdi                 REAL,
    age_penalty         REAL,
    risk_score          REAL,
    risk_level          TEXT,
    emergency_index     REAL,
    emergency_level     TEXT,
    requires_immediate_action BOOLEAN,
    structural_factor   REAL,
    repair_cost         REAL,
    repair_cost_mode    TEXT,
    rul_years           REAL,
    rul_mode            TEXT,
    priority_level      TEXT,
    recommended_action  TEXT,
    due_date            TEXT,
    simulation_timeline_json TEXT,
    features_json       TEXT,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notifications (
    notification_id INTEGER PRIMARY KEY AUTOINCREMENT,
    road_id         INTEGER,
    road_name       TEXT,
    prediction_id   INTEGER,
    session_id      TEXT,
    severity        TEXT,
    message         TEXT,
    channel         TEXT,
    recipient       TEXT,
    status          TEXT,
    is_resolved     BOOLEAN DEFAULT 0,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS complaints (
    complaint_id    TEXT PRIMARY KEY,
    road_id         INTEGER,
    road_name       TEXT,
    prediction_id   INTEGER,
    session_id      TEXT,
    department      TEXT,
    priority_level  TEXT,
    recommended_action TEXT,
    estimated_cost  REAL,
    due_date        TEXT,
    status          TEXT DEFAULT 'Submitted',
    letter_text     TEXT,
    file_path       TEXT,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reports (
    report_id       INTEGER PRIMARY KEY AUTOINCREMENT,
    road_id         INTEGER,
    session_id      TEXT,
    prediction_id   INTEGER,
    report_type     TEXT,
    file_path       TEXT NOT NULL,
    summary_json    TEXT,
    generated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_detections_road ON detections(road_id);
CREATE INDEX IF NOT EXISTS idx_detections_session ON detections(session_id);
CREATE INDEX IF NOT EXISTS idx_predictions_road ON predictions(road_id);
CREATE INDEX IF NOT EXISTS idx_notifications_road ON notifications(road_id);
CREATE INDEX IF NOT EXISTS idx_complaints_road ON complaints(road_id);
CREATE TABLE IF NOT EXISTS email_settings (
    id                  INTEGER PRIMARY KEY CHECK (id = 1),
    receiver_email      TEXT,
    auto_send_enabled   BOOLEAN DEFAULT 0,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS email_log (
    email_log_id    INTEGER PRIMARY KEY AUTOINCREMENT,
    road_id         INTEGER,
    prediction_id   INTEGER,
    receiver_email  TEXT,
    subject         TEXT,
    severity        TEXT,
    status          TEXT,
    error_message   TEXT,
    damage_class    TEXT,
    confidence      REAL,
    frame_number    INTEGER,
    image_path      TEXT,
    sent_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_reports_road ON reports(road_id);
CREATE INDEX IF NOT EXISTS idx_email_log_road ON email_log(road_id);
"""

# Canonical column set per table, used by the auto-migration step below.
# Format: {table: {column: "SQL TYPE [DEFAULT ...]"}}
_EXPECTED_COLUMNS: Dict[str, Dict[str, str]] = {
    "road_assets": {
        "road_id": "INTEGER PRIMARY KEY AUTOINCREMENT",
        "name": "TEXT",
        "asset_type": "TEXT DEFAULT 'road'",
        "created_at": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
    },
    "detections": {
        "road_id": "INTEGER",
        "road_name": "TEXT",
        "session_id": "TEXT",
        "asset_type": "TEXT DEFAULT 'road'",
        "source_type": "TEXT DEFAULT 'image'",
        "source_path": "TEXT",
        "source_filename": "TEXT",
        "annotated_path": "TEXT",
        "class_name": "TEXT",
        "confidence": "REAL",
        "area_px": "REAL",
        "bbox_x1": "REAL", "bbox_y1": "REAL", "bbox_x2": "REAL", "bbox_y2": "REAL",
        "frame_number": "INTEGER",
        "timestamp_sec": "REAL",
        "created_at": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
    },
    "predictions": {
        "road_id": "INTEGER",
        "road_name": "TEXT",
        "session_id": "TEXT",
        "asset_type": "TEXT",
        "damage_count": "INTEGER",
        "damage_percentage": "REAL",
        "severity_score": "REAL",
        "severity_class": "TEXT",
        "health_score": "REAL",
        "hdi": "REAL",
        "age_penalty": "REAL",
        "risk_score": "REAL",
        "risk_level": "TEXT",
        "emergency_index": "REAL",
        "emergency_level": "TEXT",
        "requires_immediate_action": "BOOLEAN",
        "structural_factor": "REAL",
        "repair_cost": "REAL",
        "repair_cost_mode": "TEXT",
        "rul_years": "REAL",
        "rul_mode": "TEXT",
        "priority_level": "TEXT",
        "recommended_action": "TEXT",
        "due_date": "TEXT",
        "simulation_timeline_json": "TEXT",
        "features_json": "TEXT",
        "created_at": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
    },
    "notifications": {
        "road_id": "INTEGER",
        "road_name": "TEXT",
        "prediction_id": "INTEGER",
        "session_id": "TEXT",
        "severity": "TEXT",
        "message": "TEXT",
        "channel": "TEXT",
        "recipient": "TEXT",
        "status": "TEXT",
        "is_resolved": "BOOLEAN DEFAULT 0",
        "created_at": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
    },
    "complaints": {
        "road_id": "INTEGER",
        "road_name": "TEXT",
        "prediction_id": "INTEGER",
        "session_id": "TEXT",
        "department": "TEXT",
        "priority_level": "TEXT",
        "recommended_action": "TEXT",
        "estimated_cost": "REAL",
        "due_date": "TEXT",
        "status": "TEXT DEFAULT 'Submitted'",
        "letter_text": "TEXT",
        "file_path": "TEXT",
        "created_at": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
    },
    "reports": {
        "road_id": "INTEGER",
        "session_id": "TEXT",
        "prediction_id": "INTEGER",
        "report_type": "TEXT",
        "file_path": "TEXT",
        "summary_json": "TEXT",
        "generated_at": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
    },
    "email_settings": {
        "id": "INTEGER PRIMARY KEY",
        "receiver_email": "TEXT",
        "auto_send_enabled": "BOOLEAN DEFAULT 0",
        "updated_at": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
    },
    "email_log": {
        "road_id": "INTEGER",
        "prediction_id": "INTEGER",
        "receiver_email": "TEXT",
        "subject": "TEXT",
        "severity": "TEXT",
        "status": "TEXT",
        "error_message": "TEXT",
        "damage_class": "TEXT",
        "confidence": "REAL",
        "frame_number": "INTEGER",
        "image_path": "TEXT",
        "sent_at": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
    },
}


# ---------------------------------------------------------------------
# CONNECTION HANDLING
# ---------------------------------------------------------------------
@contextmanager
def get_connection():
    """
    Yields a sqlite3 connection configured with row access by column
    name (sqlite3.Row). Commits on clean exit, rolls back on exception,
    always closes.
    """
    conn = sqlite3.connect(str(DATABASE_PATH), timeout=SQLITE_TIMEOUT_SECONDS)
    conn.row_factory = sqlite3.Row
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def _safe_list(fn):
    """Decorator: any read function that should return a List[Dict] returns [] on error instead of raising."""
    @wraps(fn)
    def wrapper(*args, **kwargs):
        try:
            return fn(*args, **kwargs)
        except Exception as e:
            logger.error(f"{fn.__name__} failed, returning [] ({e})")
            return []
    return wrapper


def _safe_dict(fn):
    """Decorator: any read function that should return a Dict returns {} on error instead of raising."""
    @wraps(fn)
    def wrapper(*args, **kwargs):
        try:
            return fn(*args, **kwargs)
        except Exception as e:
            logger.error(f"{fn.__name__} failed, returning {{}} ({e})")
            return {}
    return wrapper


def _safe_write(default=None):
    """Decorator: any write function logs and returns `default` instead of raising, so the UI never crashes."""
    def decorator(fn):
        @wraps(fn)
        def wrapper(*args, **kwargs):
            try:
                return fn(*args, **kwargs)
            except Exception as e:
                logger.error(f"{fn.__name__} failed ({e})")
                return default
        return wrapper
    return decorator


# ---------------------------------------------------------------------
# SCHEMA INITIALIZATION + AUTO-MIGRATION
# ---------------------------------------------------------------------
def _existing_columns(conn: sqlite3.Connection, table: str) -> set:
    rows = conn.execute(f"PRAGMA table_info({table})").fetchall()
    return {r["name"] for r in rows}


def _migrate_schema(conn: sqlite3.Connection) -> None:
    """
    Self-heals older database files: for every table/column this module
    expects, adds any column that's missing from the actual on-disk
    schema. This is what prevents `sqlite3.OperationalError: no such
    column: ...` when a DB created by an older version of this app is
    reused (e.g. one missing `road_id` or `road_name`).
    """
    for table, expected_cols in _EXPECTED_COLUMNS.items():
        try:
            current_cols = _existing_columns(conn, table)
        except sqlite3.OperationalError:
            # Table itself doesn't exist yet - CREATE TABLE IF NOT EXISTS
            # above should have created it; if not, skip (nothing to migrate).
            continue

        for col, col_def in expected_cols.items():
            if col in current_cols:
                continue
            if "PRIMARY KEY" in col_def.upper():
                # Can't ALTER TABLE ADD a PRIMARY KEY column after the fact.
                continue
            try:
                # ALTER TABLE ADD COLUMN doesn't accept UNIQUE/CHECK - strip
                # to a bare type + optional DEFAULT for migration safety.
                safe_def = col_def.split("CHECK(")[0].strip()
                conn.execute(f"ALTER TABLE {table} ADD COLUMN {col} {safe_def}")
                logger.info(f"Migrated schema: added {table}.{col} ({safe_def})")
            except sqlite3.OperationalError as e:
                logger.warning(f"Could not add column {table}.{col}: {e}")


def init_db() -> None:
    """
    Creates all tables/indexes if they don't already exist, then
    auto-migrates any pre-existing (older-schema) database file.
    Safe to call on every app startup; never raises.
    """
    try:
        with get_connection() as conn:
            conn.executescript(SCHEMA_SQL)
            _migrate_schema(conn)
        logger.info(f"Database initialized at {DATABASE_PATH}")
    except Exception as e:
        logger.error(f"init_db() failed: {e}")


def _row_to_dict(row: Optional[sqlite3.Row]) -> Dict:
    return dict(row) if row is not None else {}


def _rows_to_list(rows: List[sqlite3.Row]) -> List[Dict]:
    return [dict(r) for r in rows]


# =======================================================================
# 0. ROAD ASSETS
# =======================================================================
@_safe_list
def list_roads() -> List[Dict]:
    """All road/flyover assets, most recently created first."""
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT road_id, name, asset_type, created_at FROM road_assets ORDER BY created_at DESC"
        ).fetchall()
    return _rows_to_list(rows)


# Alias requested by spec - identical to list_roads().
def list_assets() -> List[Dict]:
    return list_roads()


@_safe_write(default=None)
def get_or_create_road(name: str, asset_type: str = "road") -> Optional[int]:
    """
    Returns the road_id for `name`, creating a new road_assets row if one
    doesn't already exist with that name. Existing rows are NOT
    overwritten (asset_type on an existing name is left as-is) - use
    update_road() to change an existing asset's type.
    """
    name = (name or "").strip() or "Unnamed Segment"
    with get_connection() as conn:
        row = conn.execute("SELECT road_id FROM road_assets WHERE name = ?", (name,)).fetchone()
        if row:
            return row["road_id"]
        cursor = conn.execute(
            "INSERT INTO road_assets (name, asset_type) VALUES (?, ?)", (name, asset_type or "road"),
        )
        return cursor.lastrowid


def create_road(name: str, asset_type: str = "road") -> Optional[int]:
    """Explicit create - same get-or-create semantics as get_or_create_road()."""
    return get_or_create_road(name, asset_type)


@_safe_dict
def get_road(road_id: int) -> Dict:
    with get_connection() as conn:
        row = conn.execute(
            "SELECT road_id, name, asset_type, created_at FROM road_assets WHERE road_id = ?", (road_id,)
        ).fetchone()
    return _row_to_dict(row)


@_safe_write(default=False)
def update_road(road_id: int, name: Optional[str] = None, asset_type: Optional[str] = None) -> bool:
    if name is None and asset_type is None:
        return False
    fields, params = [], []
    if name is not None:
        fields.append("name = ?")
        params.append(name)
    if asset_type is not None:
        fields.append("asset_type = ?")
        params.append(asset_type)
    params.append(road_id)
    with get_connection() as conn:
        conn.execute(f"UPDATE road_assets SET {', '.join(fields)} WHERE road_id = ?", params)
    return True


@_safe_write(default=False)
def delete_road(road_id: int) -> bool:
    """Deletes a road asset. Historical detections/predictions/etc keep their
    road_id/road_name values (soft-orphaned) rather than being cascade-deleted,
    so past inspection history is never silently lost."""
    with get_connection() as conn:
        conn.execute("DELETE FROM road_assets WHERE road_id = ?", (road_id,))
    return True


def _road_name_for(conn: sqlite3.Connection, road_id: Optional[int]) -> Optional[str]:
    """Internal helper: looks up a road's name for the denormalized road_name column."""
    if road_id is None:
        return None
    row = conn.execute("SELECT name FROM road_assets WHERE road_id = ?", (road_id,)).fetchone()
    return row["name"] if row else None


# =======================================================================
# 1. DETECTIONS
# =======================================================================
@_safe_write(default=0)
def insert_detections(
    detections: List[Dict],
    road_id: Optional[int] = None,
    session_id: Optional[str] = None,
    source_type: str = "image",
    source_path: Optional[str] = None,
    annotated_path: Optional[str] = None,
    source_filename: Optional[str] = None,
    asset_type: Optional[str] = None,
) -> int:
    """
    Bulk-inserts one row per detection dict. Detection dicts follow the
    detection_service contract: {class_name, confidence, area_px,
    bbox: (x1,y1,x2,y2), frame_number?, timestamp_sec?}.

    Returns the number of rows inserted.
    """
    if not detections:
        return 0

    with get_connection() as conn:
        road_name = _road_name_for(conn, road_id)
        rows = []
        for d in detections:
            bbox = d.get("bbox") or (None, None, None, None)
            rows.append((
                road_id, road_name, session_id, asset_type, source_type,
                source_path, source_filename, annotated_path,
                d.get("class_name", "unknown"), d.get("confidence", 0.0), d.get("area_px", 0.0),
                bbox[0], bbox[1], bbox[2], bbox[3],
                d.get("frame_number"), d.get("timestamp_sec"),
            ))
        conn.executemany(
            """INSERT INTO detections
               (road_id, road_name, session_id, asset_type, source_type,
                source_path, source_filename, annotated_path,
                class_name, confidence, area_px, bbox_x1, bbox_y1, bbox_x2, bbox_y2,
                frame_number, timestamp_sec)
               VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
            rows,
        )
    logger.info(f"Inserted {len(rows)} detections (road_id={road_id}, session_id={session_id})")
    return len(rows)


@_safe_list
def fetch_all_detections(limit: int = 1000) -> List[Dict]:
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT * FROM detections ORDER BY created_at DESC LIMIT ?", (limit,)
        ).fetchall()
    return _rows_to_list(rows)


@_safe_list
def fetch_detections_by_session(session_id: str) -> List[Dict]:
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT * FROM detections WHERE session_id = ? ORDER BY frame_number, detection_id", (session_id,)
        ).fetchall()
    return _rows_to_list(rows)


@_safe_list
def get_detection_history(road_id: Optional[int] = None, limit: int = 1000) -> List[Dict]:
    """
    All detections, most recent first. If road_id is given, filtered to
    that road/flyover only; if None, returns across every asset (used by
    the Analytics Dashboard's all-time overview).
    """
    query = "SELECT * FROM detections"
    params: tuple = ()
    if road_id is not None:
        query += " WHERE road_id = ?"
        params = (road_id,)
    query += " ORDER BY created_at DESC LIMIT ?"
    params = params + (limit,)
    with get_connection() as conn:
        rows = conn.execute(query, params).fetchall()
    return _rows_to_list(rows)


# =======================================================================
# 2. PREDICTIONS  (one row per analysis session - the decision-intelligence summary)
# =======================================================================
def _extract_prediction_fields(
    health_result: Dict, risk_result: Dict, emergency_result: Dict,
    repair_cost_result: Dict, rul_result: Dict, recommendation: Dict,
) -> Dict:
    """
    Flattens the nested score-chain dicts (see app.py's run_full_pipeline)
    into the flat column set the `predictions` table stores.
    """
    analytics = health_result.get("analytics", {}) or {}
    damage_count = (analytics.get("damage_count") or {}).get("total_count")
    damage_percentage = analytics.get("damage_percentage")
    damage_severity = analytics.get("damage_severity") or {}

    return {
        "damage_count": damage_count,
        "damage_percentage": damage_percentage,
        "severity_score": damage_severity.get("severity_score"),
        "severity_class": damage_severity.get("severity_class"),
        "health_score": health_result.get("health_score"),
        "hdi": health_result.get("hdi"),
        "age_penalty": health_result.get("age_penalty"),
        "risk_score": risk_result.get("risk_score"),
        "risk_level": risk_result.get("risk_level"),
        "emergency_index": emergency_result.get("emergency_index"),
        "emergency_level": emergency_result.get("emergency_level"),
        "requires_immediate_action": bool(emergency_result.get("requires_immediate_action", False)),
        "structural_factor": emergency_result.get("structural_factor"),
        "repair_cost": repair_cost_result.get("total_cost"),
        "repair_cost_mode": repair_cost_result.get("mode"),
        "rul_years": rul_result.get("rul_years"),
        "rul_mode": rul_result.get("mode"),
        "priority_level": recommendation.get("priority_level"),
        "recommended_action": recommendation.get("recommended_action"),
        "due_date": recommendation.get("due_date"),
    }


@_safe_write(default=None)
def insert_prediction(
    road_id: Optional[int],
    session_id: str,
    asset_type: str,
    health_result: Dict,
    risk_result: Dict,
    emergency_result: Dict,
    repair_cost_result: Dict,
    rul_result: Dict,
    recommendation: Dict,
    simulation_timeline: Optional[List[Dict]] = None,
) -> Optional[int]:
    """
    Persists one full decision-intelligence session (the rich, per-service
    result dicts app.py's run_full_pipeline() produces) as a single row,
    UPSERTing on session_id so re-running the pipeline for the same
    session updates it rather than duplicating it.

    Returns the prediction_id (existing or newly created).
    """
    fields = _extract_prediction_fields(
        health_result, risk_result, emergency_result, repair_cost_result, rul_result, recommendation,
    )
    simulation_json = json.dumps(simulation_timeline) if simulation_timeline is not None else None
    features_json = json.dumps(recommendation.get("detection_actions", []))

    with get_connection() as conn:
        road_name = _road_name_for(conn, road_id)
        existing = conn.execute(
            "SELECT prediction_id FROM predictions WHERE session_id = ?", (session_id,)
        ).fetchone()

        params = (
            road_id, road_name, asset_type,
            fields["damage_count"], fields["damage_percentage"],
            fields["severity_score"], fields["severity_class"],
            fields["health_score"], fields["hdi"], fields["age_penalty"],
            fields["risk_score"], fields["risk_level"],
            fields["emergency_index"], fields["emergency_level"], fields["requires_immediate_action"],
            fields["structural_factor"],
            fields["repair_cost"], fields["repair_cost_mode"],
            fields["rul_years"], fields["rul_mode"],
            fields["priority_level"], fields["recommended_action"], fields["due_date"],
            simulation_json, features_json,
        )

        if existing:
            conn.execute(
                """UPDATE predictions SET
                     road_id=?, road_name=?, asset_type=?,
                     damage_count=?, damage_percentage=?,
                     severity_score=?, severity_class=?,
                     health_score=?, hdi=?, age_penalty=?,
                     risk_score=?, risk_level=?,
                     emergency_index=?, emergency_level=?, requires_immediate_action=?,
                     structural_factor=?,
                     repair_cost=?, repair_cost_mode=?,
                     rul_years=?, rul_mode=?,
                     priority_level=?, recommended_action=?, due_date=?,
                     simulation_timeline_json=?, features_json=?
                   WHERE session_id=?""",
                params + (session_id,),
            )
            prediction_id = existing["prediction_id"]
        else:
            cursor = conn.execute(
                """INSERT INTO predictions
                   (road_id, road_name, asset_type,
                    damage_count, damage_percentage,
                    severity_score, severity_class,
                    health_score, hdi, age_penalty,
                    risk_score, risk_level,
                    emergency_index, emergency_level, requires_immediate_action,
                    structural_factor,
                    repair_cost, repair_cost_mode,
                    rul_years, rul_mode,
                    priority_level, recommended_action, due_date,
                    simulation_timeline_json, features_json, session_id)
                   VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
                params + (session_id,),
            )
            prediction_id = cursor.lastrowid

    logger.info(f"Prediction saved for session {session_id} (prediction_id={prediction_id})")
    return prediction_id


@_safe_write(default=None)
def insert_or_update_prediction(session_id: str, road_name: str, asset_type: str, prediction: Dict) -> None:
    """
    LEGACY flat-dict API (kept for older callers): `prediction` is
    already a flattened summary dict rather than the nested per-service
    results insert_prediction() expects. UPSERTs on session_id, keyed by
    road_name only (no road_id).
    """
    with get_connection() as conn:
        existing = conn.execute(
            "SELECT prediction_id FROM predictions WHERE session_id = ?", (session_id,)
        ).fetchone()
        params = (
            road_name, asset_type,
            prediction.get("damage_count"), prediction.get("damage_percentage"),
            prediction.get("severity_score"), prediction.get("severity_class"),
            prediction.get("health_score"), prediction.get("risk_score"), prediction.get("risk_level"),
            prediction.get("emergency_index"), prediction.get("emergency_level"),
            bool(prediction.get("requires_immediate_action", False)),
            prediction.get("repair_cost"), prediction.get("rul_years"),
            prediction.get("priority_level"), prediction.get("recommended_action"),
            prediction.get("due_date"), json.dumps(prediction.get("features_json", {})),
        )
        if existing:
            conn.execute(
                """UPDATE predictions SET
                     road_name=?, asset_type=?, damage_count=?, damage_percentage=?,
                     severity_score=?, severity_class=?,
                     health_score=?, risk_score=?, risk_level=?,
                     emergency_index=?, emergency_level=?, requires_immediate_action=?,
                     repair_cost=?, rul_years=?, priority_level=?, recommended_action=?,
                     due_date=?, features_json=?
                   WHERE session_id=?""",
                params + (session_id,),
            )
        else:
            conn.execute(
                """INSERT INTO predictions
                   (road_name, asset_type, damage_count, damage_percentage,
                    severity_score, severity_class, health_score, risk_score, risk_level,
                    emergency_index, emergency_level, requires_immediate_action,
                    repair_cost, rul_years, priority_level, recommended_action, due_date,
                    features_json, session_id)
                   VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
                params + (session_id,),
            )
    logger.info(f"[legacy insert_or_update_prediction] Prediction saved for session {session_id}")


@_safe_list
def fetch_predictions(limit: int = 500) -> List[Dict]:
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT * FROM predictions ORDER BY created_at DESC LIMIT ?", (limit,)
        ).fetchall()
    return _rows_to_list(rows)


@_safe_list
def fetch_predictions_by_road(road_name: str) -> List[Dict]:
    """LEGACY name-keyed lookup (kept for older callers)."""
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT * FROM predictions WHERE road_name = ? ORDER BY created_at ASC", (road_name,)
        ).fetchall()
    return _rows_to_list(rows)


@_safe_list
def get_predictions_history(road_id: Optional[int] = None, limit: int = 500) -> List[Dict]:
    """
    All prediction sessions, oldest first (so trend charts read left-to-
    right chronologically). If road_id is given, filtered to that asset;
    if None, returns across every asset.
    """
    query = "SELECT * FROM predictions"
    params: tuple = ()
    if road_id is not None:
        query += " WHERE road_id = ?"
        params = (road_id,)
    query += " ORDER BY created_at ASC LIMIT ?"
    params = params + (limit,)
    with get_connection() as conn:
        rows = conn.execute(query, params).fetchall()
    return _rows_to_list(rows)


# =======================================================================
# 3. NOTIFICATIONS
# =======================================================================
@_safe_write(default=0)
def insert_notification(road_id: Optional[int], prediction_id: Optional[int],
                         alert: Dict, delivery_log: List[Dict]) -> int:
    """
    Persists one row PER CHANNEL from notification_service's delivery_log
    (so the history shows exactly what was sent where), all sharing the
    same alert message/severity. Primary API - keyed by road_id.
    """
    if not delivery_log:
        return 0
    with get_connection() as conn:
        road_name = _road_name_for(conn, road_id)
        rows = [
            (
                road_id, road_name, prediction_id, alert.get("severity"), alert.get("message"),
                entry.get("channel"), entry.get("recipient"), entry.get("status"),
                bool(alert.get("is_resolved", False)),
            )
            for entry in delivery_log
        ]
        conn.executemany(
            """INSERT INTO notifications
               (road_id, road_name, prediction_id, severity, message, channel, recipient, status, is_resolved)
               VALUES (?,?,?,?,?,?,?,?,?)""",
            rows,
        )
    logger.info(f"Inserted {len(rows)} notification delivery records (road_id={road_id})")
    return len(rows)


@_safe_write(default=0)
def insert_notifications(session_id: str, road_name: str, alert: Dict, delivery_log: List[Dict]) -> int:
    """LEGACY name/session-keyed API (kept for older callers)."""
    if not delivery_log:
        return 0
    rows = [
        (
            session_id, road_name, alert.get("severity"), alert.get("message"),
            entry.get("channel"), entry.get("recipient"), entry.get("status"),
            bool(alert.get("is_resolved", False)),
        )
        for entry in delivery_log
    ]
    with get_connection() as conn:
        conn.executemany(
            """INSERT INTO notifications
               (session_id, road_name, severity, message, channel, recipient, status, is_resolved)
               VALUES (?,?,?,?,?,?,?,?)""",
            rows,
        )
    logger.info(f"[legacy insert_notifications] Inserted {len(rows)} records for session {session_id}")
    return len(rows)


@_safe_list
def fetch_notifications(limit: int = 500) -> List[Dict]:
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT * FROM notifications ORDER BY created_at DESC LIMIT ?", (limit,)
        ).fetchall()
    return _rows_to_list(rows)


@_safe_list
def get_notifications(road_id: Optional[int] = None, limit: int = 500) -> List[Dict]:
    query = "SELECT * FROM notifications"
    params: tuple = ()
    if road_id is not None:
        query += " WHERE road_id = ?"
        params = (road_id,)
    query += " ORDER BY created_at DESC LIMIT ?"
    params = params + (limit,)
    with get_connection() as conn:
        rows = conn.execute(query, params).fetchall()
    return _rows_to_list(rows)


@_safe_write(default=None)
def resolve_notifications_for_session(session_id: str) -> None:
    with get_connection() as conn:
        conn.execute("UPDATE notifications SET is_resolved = 1 WHERE session_id = ?", (session_id,))


# =======================================================================
# 4. COMPLAINTS
# =======================================================================
@_safe_write(default=None)
def insert_complaint(road_id: Optional[int], prediction_id: Optional[int],
                      complaint: Dict, letter_text: Optional[str] = None) -> None:
    """
    `complaint` is complaint_service.generate_complaint()'s output dict;
    `letter_text` is complaint_service.format_complaint_letter()'s output
    (the full plain-text grievance letter, stored directly so the
    Notifications & Complaints page can display it without touching the
    filesystem).
    """
    with get_connection() as conn:
        road_name = _road_name_for(conn, road_id)
        conn.execute(
            """INSERT OR REPLACE INTO complaints
               (complaint_id, road_id, road_name, prediction_id, department, priority_level,
                recommended_action, estimated_cost, due_date, status, letter_text)
               VALUES (?,?,?,?,?,?,?,?,?,?,?)""",
            (
                complaint["complaint_id"], road_id, road_name, prediction_id,
                complaint.get("department"), complaint.get("priority_level"),
                complaint.get("recommended_action"), complaint.get("estimated_cost"),
                complaint.get("due_date"), complaint.get("status", "Submitted"), letter_text,
            ),
        )
    logger.info(f"Complaint {complaint.get('complaint_id')} saved (road_id={road_id})")


@_safe_list
def fetch_complaints(limit: int = 500) -> List[Dict]:
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT * FROM complaints ORDER BY created_at DESC LIMIT ?", (limit,)
        ).fetchall()
    return _rows_to_list(rows)


@_safe_list
def get_complaints(road_id: Optional[int] = None, limit: int = 500) -> List[Dict]:
    query = "SELECT * FROM complaints"
    params: tuple = ()
    if road_id is not None:
        query += " WHERE road_id = ?"
        params = (road_id,)
    query += " ORDER BY created_at DESC LIMIT ?"
    params = params + (limit,)
    with get_connection() as conn:
        rows = conn.execute(query, params).fetchall()
    return _rows_to_list(rows)


# =======================================================================
# 5. REPORTS
# =======================================================================
@_safe_write(default=None)
def insert_report(
    road_id: Optional[int],
    session_id: Optional[str],
    prediction_id: Optional[int],
    summary: Optional[Dict] = None,
    report_type: str = "decision_summary",
    file_path: Optional[str] = None,
) -> Optional[int]:
    with get_connection() as conn:
        cursor = conn.execute(
            """INSERT INTO reports (road_id, session_id, prediction_id, report_type, file_path, summary_json)
               VALUES (?,?,?,?,?,?)""",
            (road_id, session_id, prediction_id, report_type, file_path or "", json.dumps(summary or {})),
        )
        report_id = cursor.lastrowid
    logger.info(f"Report ({report_type}) registered (road_id={road_id}, session_id={session_id}): {file_path}")
    return report_id


@_safe_list
def fetch_reports(limit: int = 500) -> List[Dict]:
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT * FROM reports ORDER BY generated_at DESC LIMIT ?", (limit,)
        ).fetchall()
    return _rows_to_list(rows)


@_safe_list
def get_reports(road_id: Optional[int] = None, limit: int = 500) -> List[Dict]:
    query = "SELECT * FROM reports"
    params: tuple = ()
    if road_id is not None:
        query += " WHERE road_id = ?"
        params = (road_id,)
    query += " ORDER BY generated_at DESC LIMIT ?"
    params = params + (limit,)
    with get_connection() as conn:
        rows = conn.execute(query, params).fetchall()
    return _rows_to_list(rows)


# =======================================================================
# 6. EMAIL NOTIFICATION SETTINGS + LOG
# =======================================================================
@_safe_dict
def get_email_settings() -> Dict:
    """
    Returns the single, app-wide email settings row:
        {"receiver_email": str, "auto_send_enabled": bool, "updated_at": str}
    Defaults to an empty/disabled config if never saved before.
    """
    with get_connection() as conn:
        row = conn.execute("SELECT * FROM email_settings WHERE id = 1").fetchone()
    if not row:
        return {"receiver_email": "", "auto_send_enabled": False, "updated_at": None}
    d = _row_to_dict(row)
    d["auto_send_enabled"] = bool(d.get("auto_send_enabled"))
    return d


@_safe_write(default=False)
def save_email_settings(receiver_email: str, auto_send_enabled: bool) -> bool:
    """Upserts the single email_settings row (id is always 1 - one config for the whole app)."""
    with get_connection() as conn:
        conn.execute(
            """INSERT INTO email_settings (id, receiver_email, auto_send_enabled, updated_at)
               VALUES (1, ?, ?, CURRENT_TIMESTAMP)
               ON CONFLICT(id) DO UPDATE SET
                 receiver_email = excluded.receiver_email,
                 auto_send_enabled = excluded.auto_send_enabled,
                 updated_at = CURRENT_TIMESTAMP""",
            (receiver_email, bool(auto_send_enabled)),
        )
    logger.info(f"Email settings saved (receiver={receiver_email}, auto_send={auto_send_enabled})")
    return True


@_safe_write(default=None)
def log_email_sent(
    road_id: Optional[int],
    prediction_id: Optional[int],
    receiver_email: str,
    subject: str,
    severity: str,
    status: str,
    error_message: Optional[str] = None,
) -> Optional[int]:
    """Records every email send attempt (success or failure) for audit/history."""
    with get_connection() as conn:
        cursor = conn.execute(
            """INSERT INTO email_log
               (road_id, prediction_id, receiver_email, subject, severity, status, error_message)
               VALUES (?,?,?,?,?,?,?)""",
            (road_id, prediction_id, receiver_email, subject, severity, status, error_message),
        )
        log_id = cursor.lastrowid
    logger.info(f"Email log entry #{log_id}: status={status} to={receiver_email} severity={severity}")
    return log_id


@_safe_list
def fetch_email_log(limit: int = 200) -> List[Dict]:
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT * FROM email_log ORDER BY sent_at DESC LIMIT ?", (limit,)
        ).fetchall()
    return _rows_to_list(rows)


@_safe_write(default=None)
def log_damage_email_event(
    road_id: Optional[int],
    receiver_email: str,
    subject: str,
    severity: str,
    status: str,
    damage_class: str,
    confidence: float,
    frame_number: Optional[int] = None,
    image_path: Optional[str] = None,
    error_message: Optional[str] = None,
) -> Optional[int]:
    """
    Records one EVENT-DRIVEN email alert fired during live/video detection
    (as opposed to log_email_sent(), which logs the full-pipeline
    High/Critical session alert). Both write to the same `email_log`
    table so the Notifications page shows one unified send history.
    """
    with get_connection() as conn:
        cursor = conn.execute(
            """INSERT INTO email_log
               (road_id, receiver_email, subject, severity, status,
                damage_class, confidence, frame_number, image_path, error_message)
               VALUES (?,?,?,?,?,?,?,?,?,?)""",
            (road_id, receiver_email, subject, severity, status,
             damage_class, confidence, frame_number, image_path, error_message),
        )
        log_id = cursor.lastrowid
    logger.info(
        f"Damage event email #{log_id}: status={status} class={damage_class} "
        f"conf={confidence:.2f} frame={frame_number} to={receiver_email}"
    )
    return log_id


# =======================================================================
# ANALYTICS AGGREGATION HELPERS (feed the Analytics Dashboard charts)
# =======================================================================
@_safe_list
def get_damage_distribution(road_id: Optional[int] = None) -> List[Dict]:
    """
    Total detection count per damage class, as a list of
    {"class_name", "count"} dicts (ready for pd.DataFrame + px.pie).
    Primary API - keyed by road_id.
    """
    query = "SELECT class_name, COUNT(*) as count FROM detections"
    params: tuple = ()
    if road_id is not None:
        query += " WHERE road_id = ?"
        params = (road_id,)
    query += " GROUP BY class_name ORDER BY count DESC"
    with get_connection() as conn:
        rows = conn.execute(query, params).fetchall()
    return _rows_to_list(rows)


@_safe_dict
def get_damage_class_distribution(road_name: Optional[str] = None) -> Dict[str, int]:
    """LEGACY name-keyed API (kept for older callers) - returns a dict, not a list."""
    query = "SELECT class_name, COUNT(*) as cnt FROM detections"
    params: tuple = ()
    if road_name:
        query += " WHERE road_name = ?"
        params = (road_name,)
    query += " GROUP BY class_name ORDER BY cnt DESC"
    with get_connection() as conn:
        rows = conn.execute(query, params).fetchall()
    return {r["class_name"]: r["cnt"] for r in rows}


@_safe_dict
def get_severity_class_distribution(road_name: Optional[str] = None) -> Dict[str, int]:
    """Count of analysis sessions per severity_class - feeds a severity bar chart."""
    query = "SELECT severity_class, COUNT(*) as cnt FROM predictions WHERE severity_class IS NOT NULL"
    params: tuple = ()
    if road_name:
        query += " AND road_name = ?"
        params = (road_name,)
    query += " GROUP BY severity_class"
    with get_connection() as conn:
        rows = conn.execute(query, params).fetchall()
    return {r["severity_class"]: r["cnt"] for r in rows}


@_safe_list
def get_risk_trend(road_name: Optional[str] = None, limit: int = 100) -> List[Dict]:
    """Chronological (session, risk_score, emergency_index) history."""
    query = "SELECT session_id, road_name, risk_score, emergency_index, created_at FROM predictions"
    params: tuple = ()
    if road_name:
        query += " WHERE road_name = ?"
        params = (road_name,)
    query += " ORDER BY created_at ASC LIMIT ?"
    params = params + (limit,)
    with get_connection() as conn:
        rows = conn.execute(query, params).fetchall()
    return _rows_to_list(rows)


@_safe_list
def get_repair_cost_trend(road_name: Optional[str] = None, limit: int = 100) -> List[Dict]:
    """Chronological repair-cost history."""
    query = "SELECT session_id, road_name, repair_cost, created_at FROM predictions WHERE repair_cost IS NOT NULL"
    params: tuple = ()
    if road_name:
        query += " AND road_name = ?"
        params = (road_name,)
    query += " ORDER BY created_at ASC LIMIT ?"
    params = params + (limit,)
    with get_connection() as conn:
        rows = conn.execute(query, params).fetchall()
    return _rows_to_list(rows)


@_safe_dict
def get_summary_kpis() -> Dict:
    """Headline counters for the dashboard home/overview page."""
    with get_connection() as conn:
        total_detections = conn.execute("SELECT COUNT(*) c FROM detections").fetchone()["c"]
        total_sessions = conn.execute("SELECT COUNT(*) c FROM predictions").fetchone()["c"]
        urgent_count = conn.execute(
            "SELECT COUNT(*) c FROM predictions WHERE priority_level = 'urgent'"
        ).fetchone()["c"]
        open_complaints = conn.execute(
            "SELECT COUNT(*) c FROM complaints WHERE status != 'Resolved'"
        ).fetchone()["c"]
        avg_health = conn.execute("SELECT AVG(health_score) a FROM predictions").fetchone()["a"]
    return {
        "total_detections": total_detections,
        "total_sessions": total_sessions,
        "urgent_count": urgent_count,
        "open_complaints": open_complaints,
        "avg_health_score": round(avg_health, 2) if avg_health is not None else None,
    }


# ---------------------------------------------------------------------
# CLI smoke test
# ---------------------------------------------------------------------
if __name__ == "__main__":
    init_db()

    rid = get_or_create_road("Anna Salai Flyover", "flyover")
    print("Road ID:", rid)
    print("Roads:", list_roads())

    sid = "smoketest-session-1"
    insert_detections(
        [
            {"class_name": "pothole", "confidence": 0.91, "area_px": 6200, "bbox": (10, 10, 60, 60)},
            {"class_name": "crack", "confidence": 0.68, "area_px": 2100, "bbox": (100, 100, 140, 160)},
        ],
        road_id=rid, session_id=sid, source_type="image", source_path="test.jpg",
    )

    prediction_id = insert_prediction(
        rid, sid, "flyover",
        health_result={"health_score": 65.4, "hdi": 0.35, "age_penalty": 4.5,
                        "analytics": {"damage_count": {"total_count": 2}, "damage_percentage": 3.2,
                                      "damage_severity": {"severity_score": 0.62, "severity_class": "High"}}},
        risk_result={"risk_score": 41.2, "risk_level": "Medium"},
        emergency_result={"emergency_index": 28.0, "emergency_level": "Low",
                           "requires_immediate_action": False, "structural_factor": 0.0},
        repair_cost_result={"total_cost": 12500.0, "mode": "heuristic"},
        rul_result={"rul_years": 22.3, "mode": "heuristic"},
        recommendation={"priority_level": "medium", "recommended_action": "Structural Inspection",
                         "due_date": "2026-08-01", "detection_actions": []},
        simulation_timeline=[],
    )
    print("Prediction ID:", prediction_id)

    insert_notification(rid, prediction_id, {"severity": "medium", "message": "test alert"},
                         [{"channel": "dashboard", "recipient": "dashboard", "status": "queued"}])

    insert_complaint(rid, prediction_id, {
        "complaint_id": "CMP-TEST-0001", "department": "Bridges & Structures Division",
        "priority_level": "medium", "recommended_action": "Structural Inspection",
        "estimated_cost": 12500.0, "due_date": "2026-08-01", "status": "Submitted",
    }, letter_text="Dear Sir/Madam, ...")

    insert_report(rid, sid, prediction_id, summary={"note": "smoke test"}, report_type="inspection",
                  file_path="data/exports/reports/test_report.pdf")

    print("Detections:", fetch_detections_by_session(sid))
    print("Damage distribution:", get_damage_distribution(rid))
    print("Predictions history:", get_predictions_history(rid))
    print("Notifications:", get_notifications(rid))
    print("Complaints:", get_complaints(rid))
    print("Reports:", get_reports(rid))
    print("KPIs:", get_summary_kpis())